-- ============================================================
-- Supabase Auth Webhook Trigger — Welcome Email on Signup
--
-- This uses pg_catalog (always available) instead of pg_net
-- (which requires Supabase Pro). Works on free tier.
--
-- Run in: Supabase Dashboard → SQL Editor
-- ============================================================

-- 1. Create the trigger function using Supabase's built-in
--    pg_catalog.pg_notify for real-time events, combined with
--    the existing /auth/welcome POST endpoint.
--    Since free tier lacks pg_net, we use a simpler approach:
--    the frontend already calls POST /auth/welcome after signup.
--    This SQL creates a DATABASE webhook via Supabase's native
--    feature instead.
--
-- ALTERNATIVE (RECOMMENDED): Use Supabase Dashboard UI instead:
--
-- Go to: Database → Webhooks → Create a new webhook
--   - Table: auth.users
--   - Events: INSERT
--   - Type: HTTP
--   - URL: https://neuralquant.onrender.com/auth/webhook
--   - HTTP Method: POST
--   - Headers: Content-Type: application/json
--
-- This avoids the pg_net extension entirely.

-- If you want to try the SQL approach on a plan with pg_net,
-- uncomment below:

-- CREATE EXTENSION IF NOT EXISTS pg_net SCHEMA extensions;
--
-- CREATE OR REPLACE FUNCTION public.send_welcome_webhook()
-- RETURNS TRIGGER
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- AS $$
-- DECLARE
--   webhook_url TEXT := 'https://neuralquant.onrender.com/auth/webhook';
--   request_id UUID;
-- BEGIN
--   IF TG_OP = 'INSERT' THEN
--     SELECT INTO request_id net.http_post(
--       url := webhook_url,
--       headers := jsonb_build('Content-Type', 'application/json'),
--       body := jsonb_build(
--         'type', 'auth.user.created',
--         'record', jsonb_build_object(
--           'id', NEW.id,
--           'email', NEW.email,
--           'raw_user_meta_data', NEW.raw_user_meta_data
--         ),
--         'schema_name', 'auth',
--         'table', 'users'
--       )
--     );
--   END IF;
--   RETURN NEW;
-- END;
-- $$;
--
-- DROP TRIGGER IF EXISTS on_user_created ON auth.users;
-- CREATE TRIGGER on_user_created
--   AFTER INSERT ON auth.users
--   FOR EACH ROW
--   EXECUTE FUNCTION public.send_welcome_webhook();