-- Auto-generated from live Supabase PostgREST spec. Demo stack only.

CREATE TABLE IF NOT EXISTS "score_cache" (
    "ticker" text,
    "market" text,
    "sector" text,
    "composite_score" numeric,
    "rank_score" integer,
    "value_percentile" numeric,
    "momentum_percentile" numeric,
    "quality_percentile" numeric,
    "low_vol_percentile" numeric,
    "short_interest_percentile" numeric,
    "current_price" numeric,
    "analyst_target" numeric,
    "pe_ttm" numeric,
    "market_cap" numeric,
    "week52_high" numeric,
    "week52_low" numeric,
    "computed_at" timestamp with time zone,
    "momentum_raw" numeric,
    "gross_profit_margin" numeric,
    "piotroski" integer,
    "pb_ratio" numeric,
    "beta" numeric,
    "realized_vol_1y" numeric,
    "short_interest_pct" numeric,
    "insider_cluster_score" numeric,
    "accruals_ratio" numeric,
    "revenue_growth_yoy" numeric,
    "debt_equity" numeric,
    "long_name" text,
    "industry" text,
    "analyst_rec" text,
    "earnings_date" text,
    "dividend_yield" numeric,
    "roe" double precision,
    "fcf_yield" double precision
);

CREATE TABLE IF NOT EXISTS "anjali_enrichment" (
    "id" uuid,
    "ticker" text,
    "market" text,
    "index_group" text,
    "sales_yoy_growth" numeric,
    "net_profit_yoy_growth" numeric,
    "sales_ttm_growth" numeric,
    "net_profit_ttm_growth" numeric,
    "qoq_sales_growth" numeric,
    "qoq_profit_growth" numeric,
    "return_3m" numeric,
    "return_6m" numeric,
    "return_1yr" numeric,
    "return_2yr" numeric,
    "pe_ratio" numeric,
    "future_pe" numeric,
    "ttm_peg" numeric,
    "future_peg" numeric,
    "pb_ratio" numeric,
    "ev_sales" numeric,
    "ev_ebitda" numeric,
    "market_cap_bn" numeric,
    "revenue_bn" numeric,
    "ttm_revenue_bn" numeric,
    "qtr_std" numeric,
    "yr_std" numeric,
    "qtr_beta" numeric,
    "yr_beta" numeric,
    "dii_quarter" numeric,
    "dii_1yr" numeric,
    "fii_quarter" numeric,
    "fii_1yr" numeric,
    "return_score" numeric,
    "growth_score" numeric,
    "valuation_score" numeric,
    "risk_score" numeric,
    "composite_anjali_score" numeric,
    "loss_profit_yoy" boolean,
    "loss_profit_ttm" boolean,
    "loss_profit_qoq" boolean,
    "data_collected_at" timestamp with time zone,
    "refreshed_at" timestamp with time zone,
    "alpha" numeric,
    "final_score" numeric,
    "rebalance_date" date,
    "future_return" numeric,
    "strategy_stocks" text,
    "stocks_list" text,
    "g_score" numeric,
    "risk_eff_score" numeric,
    "irs_raw" numeric,
    "irs_pct" numeric
);

CREATE TABLE IF NOT EXISTS "quantfactor_universe" (
    "ticker" text,
    "market" text,
    "index_group" text,
    "sector" text,
    "sub_sector" text,
    "sales_yoy_growth" numeric,
    "net_profit_yoy_growth" numeric,
    "sales_ttm_1yr_growth" numeric,
    "net_profit_ttm_1yr_growth" numeric,
    "qoq_sales_growth" numeric,
    "qoq_profit_growth" numeric,
    "return_3m" numeric,
    "return_6m" numeric,
    "return_1yr" numeric,
    "return_2yr" numeric,
    "pe_ratio" numeric,
    "future_pe" numeric,
    "ttm_peg" numeric,
    "future_peg" numeric,
    "pb_ratio" numeric,
    "ev_sales" numeric,
    "ev_ebitda" numeric,
    "market_cap_b" numeric,
    "revenue_b" numeric,
    "ttm_revenue_b" numeric,
    "qtr_std" numeric,
    "yr_std" numeric,
    "qtr_beta" numeric,
    "yr_beta" numeric,
    "dii_quarter" numeric,
    "dii_1yr" numeric,
    "fii_quarter" numeric,
    "fii_1yr" numeric,
    "return_score" numeric,
    "growth_score" numeric,
    "valuation_score" numeric,
    "risk_score" numeric,
    "composite_score" numeric,
    "g_score" numeric,
    "risk_eff_score" numeric,
    "irs_raw" numeric,
    "irs_pct" numeric,
    "alpha_score" numeric,
    "final_score" numeric,
    "rebalance_date" text,
    "future_return" numeric,
    "strategy_stocks" text,
    "stocks_list" text,
    "loss_profit_yoy" boolean,
    "loss_profit_ttm" boolean,
    "loss_profit_qoq" boolean,
    "computed_at" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "quarterly_test_runs" (
    "id" uuid,
    "run_date" date,
    "quarter" text,
    "test_type" text,
    "selected_tickers" jsonb,
    "selection_criteria" jsonb,
    "anjali_snapshot" jsonb,
    "created_at" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "quarterly_test_results" (
    "id" uuid,
    "run_id" uuid,
    "ticker" text,
    "market" text,
    "entry_price" numeric,
    "exit_price" numeric,
    "return_pct" numeric,
    "benchmark_return_pct" numeric,
    "alpha" numeric,
    "evaluated_at" date,
    "notes" text
);
