-- Migration 013: signal_log table
-- Stores every trading signal generated by the risk engine for calibration tracking.
-- Written by CalibrationTracker (packages/signals/src/nq_signals/calibration.py).
-- Read by /trade/calibration endpoint for accuracy metrics.

CREATE TABLE IF NOT EXISTS signal_log (
    id BIGSERIAL PRIMARY KEY,
    ticker TEXT NOT NULL,
    market TEXT NOT NULL DEFAULT 'US',
    signal_date TIMESTAMPTZ NOT NULL,
    composite_score DOUBLE PRECISION NOT NULL,
    edge DOUBLE PRECISION NOT NULL,
    direction TEXT NOT NULL DEFAULT 'bullish',
    entry_price DOUBLE PRECISION NOT NULL,
    bet DOUBLE PRECISION DEFAULT 0.0,
    strategy TEXT DEFAULT 'default',
    exit_price DOUBLE PRECISION,
    pnl DOUBLE PRECISION,
    resolved BOOLEAN NOT NULL DEFAULT false,
    resolution_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for calibration queries: resolved signals in date range
CREATE INDEX IF NOT EXISTS idx_signal_log_resolved_date ON signal_log (market, resolved, signal_date);
CREATE INDEX IF NOT EXISTS idx_signal_log_ticker ON signal_log (ticker, market);

-- RLS: allow public reads (trade page is public)
ALTER TABLE signal_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read signal log" ON signal_log FOR SELECT USING (true);
CREATE POLICY "Service role write signal log" ON signal_log FOR INSERT WITH CHECK (true);
CREATE POLICY "Service role update signal log" ON signal_log FOR UPDATE USING (true);
